/// noctalia-gtk
///
/// Watches ~/.config/noctalia/colors.json and settings.json for changes,
/// then writes matching GTK 3 and GTK 4 CSS overrides and updates gsettings
/// so that GTK apps (like Nyxt) follow the active Noctalia theme.
///
/// Run on login. Add to your niri/autostart or systemd user session.

use inotify::{EventMask, Inotify, WatchMask};
use serde::Deserialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

// ── Noctalia color schema ────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NoctaliaColors {
    m_error: String,
    m_on_error: String,
    m_hover: String,
    m_on_hover: String,
    m_on_primary: String,
    m_on_secondary: String,
    m_on_surface: String,
    m_on_surface_variant: String,
    m_on_tertiary: String,
    m_outline: String,
    m_primary: String,
    m_secondary: String,
    m_shadow: String,
    m_surface: String,
    m_surface_variant: String,
    m_tertiary: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ColorSchemes {
    dark_mode: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct NoctaliaSettings {
    color_schemes: ColorSchemes,
}

// ── GTK CSS generation ───────────────────────────────────────────────────────

fn generate_gtk3_css(c: &NoctaliaColors) -> String {
    format!(
        r#"/* Generated by noctalia-gtk — do not edit manually */

@define-color accent_color {primary};
@define-color accent_bg_color {primary};
@define-color accent_fg_color {on_primary};
@define-color window_bg_color {surface};
@define-color window_fg_color {on_surface};
@define-color view_bg_color {surface_variant};
@define-color view_fg_color {on_surface};
@define-color headerbar_bg_color {surface_variant};
@define-color headerbar_fg_color {on_surface};
@define-color headerbar_border_color {outline};
@define-color sidebar_bg_color {surface};
@define-color sidebar_fg_color {on_surface};
@define-color card_bg_color {surface_variant};
@define-color card_fg_color {on_surface};
@define-color popover_bg_color {surface_variant};
@define-color popover_fg_color {on_surface};
@define-color dialog_bg_color {surface};
@define-color dialog_fg_color {on_surface};
@define-color error_color {error};
@define-color success_color {primary};
@define-color warning_color {tertiary};

/* Window and titlebar */
headerbar,
.titlebar {{
    background-color: {surface_variant};
    color: {on_surface};
    border-bottom: 1px solid {outline};
    box-shadow: none;
}}

headerbar:backdrop,
.titlebar:backdrop {{
    background-color: {surface};
    color: {on_surface_variant};
}}

/* Window background */
window,
.background {{
    background-color: {surface};
    color: {on_surface};
}}

/* Buttons */
button {{
    background-color: {surface_variant};
    color: {on_surface};
    border: 1px solid {outline};
    border-radius: 6px;
}}

button:hover {{
    background-color: {hover};
    color: {on_hover};
}}

button:active,
button:checked {{
    background-color: {primary};
    color: {on_primary};
}}

/* Suggested/accent action button */
button.suggested-action {{
    background-color: {primary};
    color: {on_primary};
}}

button.destructive-action {{
    background-color: {error};
    color: {on_error};
}}

/* Text entries */
entry {{
    background-color: {surface_variant};
    color: {on_surface};
    border: 1px solid {outline};
    border-radius: 6px;
}}

entry:focus {{
    border-color: {primary};
}}

/* Selection */
*:selected,
selection {{
    background-color: {primary};
    color: {on_primary};
}}

/* Scrollbars */
scrollbar slider {{
    background-color: {outline};
    border-radius: 4px;
}}

scrollbar slider:hover {{
    background-color: {secondary};
}}

/* Menus and popovers */
menu,
.menu,
popover {{
    background-color: {surface_variant};
    color: {on_surface};
    border: 1px solid {outline};
}}

menuitem:hover {{
    background-color: {hover};
    color: {on_hover};
}}

/* Sidebar */
.sidebar {{
    background-color: {surface};
    color: {on_surface};
    border-right: 1px solid {outline};
}}

/* Notebook tabs */
notebook tab {{
    background-color: {surface};
    color: {on_surface_variant};
}}

notebook tab:checked {{
    background-color: {surface_variant};
    color: {on_surface};
}}

/* Separators */
separator {{
    background-color: {outline};
}}

/* Links */
*:link {{
    color: {secondary};
}}

*:visited {{
    color: {tertiary};
}}
"#,
        primary = c.m_primary,
        on_primary = c.m_on_primary,
        secondary = c.m_secondary,
        tertiary = c.m_tertiary,
        surface = c.m_surface,
        on_surface = c.m_on_surface,
        surface_variant = c.m_surface_variant,
        on_surface_variant = c.m_on_surface_variant,
        outline = c.m_outline,
        error = c.m_error,
        on_error = c.m_on_error,
        hover = c.m_hover,
        on_hover = c.m_on_hover,
    )
}

fn generate_gtk4_css(c: &NoctaliaColors) -> String {
    // GTK4 uses the same @define-color variables but the widget CSS differs slightly
    format!(
        r#"/* Generated by noctalia-gtk — do not edit manually */

@define-color accent_color {primary};
@define-color accent_bg_color {primary};
@define-color accent_fg_color {on_primary};
@define-color window_bg_color {surface};
@define-color window_fg_color {on_surface};
@define-color view_bg_color {surface_variant};
@define-color view_fg_color {on_surface};
@define-color headerbar_bg_color {surface_variant};
@define-color headerbar_fg_color {on_surface};
@define-color headerbar_border_color {outline};
@define-color sidebar_bg_color {surface};
@define-color sidebar_fg_color {on_surface};
@define-color card_bg_color {surface_variant};
@define-color card_fg_color {on_surface};
@define-color popover_bg_color {surface_variant};
@define-color popover_fg_color {on_surface};
@define-color dialog_bg_color {surface};
@define-color dialog_fg_color {on_surface};
@define-color error_color {error};
@define-color success_color {primary};
@define-color warning_color {tertiary};

/* Titlebar / headerbar */
headerbar {{
    background-color: {surface_variant};
    color: {on_surface};
}}

headerbar:backdrop {{
    background-color: {surface};
    color: {on_surface_variant};
}}

/* Window */
window {{
    background-color: {surface};
    color: {on_surface};
}}

/* Accent / suggested action */
button.suggested-action {{
    background-color: {primary};
    color: {on_primary};
}}

button.destructive-action {{
    background-color: {error};
    color: {on_error};
}}

/* Selection */
selection {{
    background-color: {primary};
    color: {on_primary};
}}

/* Links */
link {{
    color: {secondary};
}}
"#,
        primary = c.m_primary,
        on_primary = c.m_on_primary,
        secondary = c.m_secondary,
        on_surface = c.m_on_surface,
        on_surface_variant = c.m_on_surface_variant,
        surface = c.m_surface,
        surface_variant = c.m_surface_variant,
        outline = c.m_outline,
        error = c.m_error,
        on_error = c.m_on_error,
        tertiary = c.m_tertiary,
    )
}

// ── gsettings ────────────────────────────────────────────────────────────────

fn set_gsettings(dark_mode: bool) {
    let scheme = if dark_mode {
        "prefer-dark"
    } else {
        "prefer-light"
    };

    let _ = Command::new("gsettings")
        .args(["set", "org.gnome.desktop.interface", "color-scheme", scheme])
        .status();

    // Also set gtk-theme to Adwaita so our CSS overrides apply cleanly
    let gtk_theme = if dark_mode { "Adwaita-dark" } else { "Adwaita" };
    let _ = Command::new("gsettings")
        .args(["set", "org.gnome.desktop.interface", "gtk-theme", gtk_theme])
        .status();

    println!(
        "[noctalia-gtk] gsettings → color-scheme={} gtk-theme={}",
        scheme, gtk_theme
    );
}

// ── File writing ─────────────────────────────────────────────────────────────

fn write_gtk_css(colors: &NoctaliaColors, dark_mode: bool) {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());

    let gtk3_dir = PathBuf::from(&home).join(".config/gtk-3.0");
    let gtk4_dir = PathBuf::from(&home).join(".config/gtk-4.0");

    fs::create_dir_all(&gtk3_dir).ok();
    fs::create_dir_all(&gtk4_dir).ok();

    let gtk3_css = generate_gtk3_css(colors);
    let gtk4_css = generate_gtk4_css(colors);

    fs::write(gtk3_dir.join("gtk.css"), &gtk3_css)
        .expect("Failed to write gtk-3.0/gtk.css");
    fs::write(gtk4_dir.join("gtk.css"), &gtk4_css)
        .expect("Failed to write gtk-4.0/gtk.css");

    println!(
        "[noctalia-gtk] Wrote GTK CSS ({} mode)",
        if dark_mode { "dark" } else { "light" }
    );
}

// ── Read + apply ─────────────────────────────────────────────────────────────

fn apply(colors_path: &Path, settings_path: &Path) {
    let colors_raw = match fs::read_to_string(colors_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[noctalia-gtk] Failed to read colors.json: {}", e);
            return;
        }
    };

    let settings_raw = match fs::read_to_string(settings_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[noctalia-gtk] Failed to read settings.json: {}", e);
            return;
        }
    };

    let colors: NoctaliaColors = match serde_json::from_str(&colors_raw) {
        Ok(c) => c,
        Err(e) => {
            eprintln!("[noctalia-gtk] Failed to parse colors.json: {}", e);
            return;
        }
    };

    let settings: NoctaliaSettings = match serde_json::from_str(&settings_raw) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("[noctalia-gtk] Failed to parse settings.json: {}", e);
            return;
        }
    };

    let dark_mode = settings.color_schemes.dark_mode;
    write_gtk_css(&colors, dark_mode);
    set_gsettings(dark_mode);
}

// ── Main ─────────────────────────────────────────────────────────────────────

fn main() {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    let noctalia_dir = PathBuf::from(&home).join(".config/noctalia");
    let colors_path = noctalia_dir.join("colors.json");
    let settings_path = noctalia_dir.join("settings.json");

    // Apply immediately on startup
    println!("[noctalia-gtk] Starting — applying current theme...");
    apply(&colors_path, &settings_path);

    // Watch for changes
    let mut inotify = Inotify::init().expect("Failed to init inotify");

    inotify
        .watches()
        .add(&noctalia_dir, WatchMask::CLOSE_WRITE | WatchMask::MOVED_TO)
        .expect("Failed to watch noctalia config dir");

    println!("[noctalia-gtk] Watching {:?} for changes...", noctalia_dir);

    let mut buffer = [0u8; 4096];
    loop {
        let events = inotify
            .read_events_blocking(&mut buffer)
            .expect("Failed to read inotify events");

        let mut changed = false;
        for event in events {
            if event.mask.contains(EventMask::CLOSE_WRITE)
                || event.mask.contains(EventMask::MOVED_TO)
            {
                if let Some(name) = event.name {
                    let name = name.to_string_lossy();
                    if name == "colors.json" || name == "settings.json" {
                        changed = true;
                    }
                }
            }
        }

        if changed {
            println!("[noctalia-gtk] Change detected — reapplying theme...");
            // Small delay to let noctalia finish writing
            std::thread::sleep(std::time::Duration::from_millis(200));
            apply(&colors_path, &settings_path);
        }
    }
}
